#!/bin/sh
if ! getent group forge 1> /dev/null; then
     addgroup --quiet --system forge
fi

if ! getent passwd forge 1> /dev/null; then
    adduser --quiet \
            --shell /bin/bash \
            --system \
            --ingroup forge \
            --home /var/lib/puppet-anvil \
            --disabled-password \
            forge
fi
