#!/bin/sh
if ! getent group forge 1> /dev/null; then
     addgroup --quiet --system forge
fi

if ! getent passwd forge 1> /dev/null; then
    adduser --quiet \
            --system \
            --ingroup forge \
            --no-create-home \
            --disabled-password \
            forge
fi